 # For details on how this file works refer to:
 #   - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  #  - Check for updates once a week
  #  - Group all updates into a single PR
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-actions:
        patterns: [ "*" ]
  
  # Maintain dependencies for Python packages
  - package-ecosystem: pip
    directory: /oidc-controller
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Canada/Pacific

  # Maintain dependencies for Vue
  - package-ecosystem: npm
    directory: /demo/vue/app
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Canada/Pacific

  # Maintain dependencies for docker
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Canada/Pacific
  
    # Maintain dependencies for docker
  - package-ecosystem: docker
    directory: /demo/vue
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Canada/Pacific
