name: Publish VC-AuthN Image
run-name: Publish VC-AuthN ${{ inputs.tag || github.event.release.tag_name }} Image
on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag"
        required: true
        type: string
      platforms:
        description: "Platforms - Comma separated list of the platforms to support."
        required: true
        default: linux/amd64
        type: string
      ref:
        description: "Optional - The branch, tag or SHA to checkout."
        required: false
        type: string

env:
  PLATFORMS: ${{ inputs.platforms || 'linux/amd64,linux/arm64' }}

jobs:
  publish-image:
    if: github.repository_owner == 'bcgov'
    strategy:
      fail-fast: false

    name: Publish VC-AuthN Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || '' }}

      - name: Gather image info
        id: info
        run: |
          echo "repo-owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.info.outputs.repo-owner }}/vc-authn-oidc
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=pr
            type=sha

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: docker/oidc-controller/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: main
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: ${{ env.PLATFORMS }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
